export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_START = "LOGOUT_USER_START";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";